### ISSUE TITLE
Regexes to share?

### ISSUE THREAD

**Issue by 0ut0fb0unds** [malwareinfosec/EKFiddle#1]
Do you have any pre-built regexes to share? 

I have malicious traffic (Rig EK) in Fiddler, when I click Run Regexes it says no malicious traffic has been found.

Looking at EKFiddle\Regexes\URLRegexes.txt and EKFiddle\Regexes\HeaderRegexes.txt both files are empty expect for the instructions at the top.

**Comment by malwareinfosec** [comment]
Hey, sorry for the long delayed reply!
I thought about including pre-built regexes but there were a few issues:
- regexes are time sensitive, so unless they were very generic, you would want to regularly update them
- some regexes are sensitive, as in not necessarily publicly shareable

Also, the purpose of this tool is to be a framework, not necessarily provide all the data. Same goes for the VPN feature... by default it won't work if you have no ovpn files. Should I provide VPN files? Again, this is the framework designed to give those options, but there's a lot of responsibilities if I started sharing ovpn files...

I may revisit this issue at some point... in the meantime, building your own regexes is easy... [Regex name] [tab] [regex].

Thanks for checking this project out!
