### ISSUE TITLE
EKFiddle2Yara

### ISSUE THREAD

**Issue by MFMokbel** [malwareinfosec/EKFiddle#5]
In case someone is interested in converting EKFiddle rules to Yara rules, I wrote this tool [EKFiddle2Yara](https://github.com/MFMokbel/EKFiddle2Yara) that does just that.

**Comment by malwareinfosec** [comment]
Hi, this is great work!
Btw, EKFiddle also supports YARA rules: https://github.com/malwareinfosec/EKFiddle/raw/master/Screenshots/yara.png

**Comment by MFMokbel** [comment]
Ah, that's good to know! Thank you.
